- _posts/2014-07-02-turn-raw-data-into-a-picture-framebuffer.md
Signed-off-by: WEN Pingbo <wengpingbo@gmail.com>
> rewrite post turn-raw-data-into-a-picture-framebuffer

- _data/people.yml
> taohl 作者信息添加

- .gitignore
Signed-off-by: Peng Jingwen <pengsrc@icloud.com>
> Ignore IDEA

- _posts/2015-10-10-linux-kernel-4.2-highlights.md
Using kramdown format to automatic link
> Post linux kernel 4.2 v2

- _data/people.yml
Signed-off-by: Li Zhaozhong <ldm5235@gmail.com>
> Add Jason Lee's author info

- _posts/2015-11-07-tinylab-weekly.md
泰晓周报：开篇，确认每条基本布局：
[标题](http://xxx)
引用新闻几句，作为简要
评论
> Add tinylab weekly: Nov / 1st / 2015

- _includes/themes/tinylab.org/weekly.html
- _layouts/weekly.html
- _posts/2015-11-07-tinylab-weekly-11-1st-2015.md
- assets/themes/tinylab.org/css/style.css
纠结最终我还是觉得目前结构化的 weekly 不妥，主要理由是：
- quote 可能有多段
- comment 可能有多段（特别是 comments 可能会有发挥）
结构化以后，写 quote 和 comment 束手束脚，并且当前实现只能在一个 <p> 中。即便支持了，写起来也是二级层级，太复杂了：
- title:..
- comment:
- comment:
- quote:
故还是从 post.html fork 出一个模版 weekly，主要内容还是用 markdown 来写，配合class=weekly 的 style 来覆盖掉部分默认 style
> Dedicated layout and style for weekly

- _posts/2015-11-22-tinylab-weekly-11-3rd-2015.md
请在明天 merge。还有与平波 kernel summit 2015 的 modification 一起 merge
> add tinylab weekly: Nov / 3rd / 2015

- _data/people.yml
- _posts/2016-06-12-qingcloud-jobs.md
Signed-off-by: Feng Sun <loyou85@gmail.com>
> Update Qingcloud HR contact info

- _data/people.yml
Signed-off-by: Yupeng Li <ypli15@lzu.edu.cn>
> add the personal information of Li Yupeng

- _data/people.yml
Signed-off-by: Tacinight <tacingiht@gmail.com>
> add the personal information of Zhao Yimin

- pages/books/lwn.md
> updated lwn project page 2017 Nov, 20

- _posts/2017-10-09-22-55-32-lwn-kernel-index.md
- _posts/2017-11-26-16-45-58-lwn-240474-cfs-group-scheduling.md
Signed-off-by: Yupeng Li <ypli15@lzu.edu.cn>
> the transation of lwn-240474

- _posts/2017-10-09-22-55-32-lwn-kernel-index.md
- _posts/2017-11-28-09-50-24-lwn-576276-the-btrfs-filesystem-an-introduction.md
> lwn: add 'The btrfs filesystem: an introduction'

- _posts/2017-11-28-09-50-24-lwn-576276-the-btrfs-filesystem-an-introduction.md
> update lwn-576276: the btrfs filesystem, an introduction

- _posts/2017-12-20-22-55-32-lwn-kernel-index.md
- _posts/2017-12-27-10-42-35-lwn-577218-btrfs-getting-started.md
> lwn 577218: btrfs getting started

- _data/people.yml
update zhangfan's person information
> update persopn information

- _posts/2017-12-20-22-55-32-lwn-kernel-index.md
- _posts/2018-01-10-10-15-10-lwn-577961-btrfs-working-with-multiple-devices.md
> lwn 577961: btrfs working with multiple devices

- _posts/2017-12-20-22-55-32-lwn-kernel-index.md
- _posts/2018-01-29-10-32-43-lwn-718803-filesystem-management-interfaces.md
> lwn 718803: filesystem management interfaces

- _data/people.yml
Signed-off-by: KooLi2015 <myothers2014@126.com>
> people: add li feng

- _data/people.yml
Signed-off-by: darmac <darmac@163.com>
> add darmac(XIAO JUN)'s info in people.yml

- _posts/2018-06-10-10-26-00-lwn-70465-bringing-kgdb-into-2.6.md
Signed-off-by: darmac <darmac@163.com>
> lwn 70465 bringing kgdb into 2.6

- _posts/2018-10-29-21-58-23-lwn-105021-active-memory-defragmentation.md
> lwn 105021: active memory defragmentation

- _posts/2018-10-31-09-19-17-lwn-155344-introducing-gfp_t.md
- _posts/2018-11-07-21-58-23-lwn-105021-active-memory-defragmentation.md
201：简单修改了标题中的拼写错误 
202：
- active 的翻译
- 补上原文中遗漏的链接
- 引用 Marcelo 说话部分文字格式纠正
> fixed issue 201 & 202

- _data/people.yml
- _posts/2019-06-20-15-09-48-ustc-lug.md
Signed-off-by: OrexZ <darlingrex.mz@gmail.com>
> post: add lug@ustc introducing.

- _posts/2019-07-20-15-33-00-linux-profiling-methods-overview.md
为方便介绍期间 => 为方便介绍起见（百度，曰：为...起见，语病，只要为，或者只要起见即可） => 为方便介绍
> posts/2019-07-20-15-33-00-linux-profiling-methods-overview.md: fix typo

- _posts/2019-08-28-13-53-24-disable-compiler-optimization.md
> post: publish disable-compiler-optimization

- _posts/2019-08-31-13-53-02-the-code-and-revolution-os.md
> post: publish the-code-and-revolution-os

- _posts/2019-08-30-13-35-26-tinylab-weekly-08-5th-2019.md
- _posts/2019-09-02-15-42-13-running-elf-in-a-micro-system.md
> post: publish running-elf-in-a-micro-system

- _posts/2019-09-03-13-29-52-lwn-230574-schedulers-plot-thickens.md
> post: publish lwn-230574-schedulers-plot-thickens

- _posts/2019-09-15-14-04-49-tinylab-weekly-09-2nd-2019.md
- _posts/2019-09-17-15-08-44-lwn-415740-tty-based-group-scheduling.md
> post: publish lwn-415740-tty-based-group-scheduling

- _posts/2019-09-17-15-08-44-lwn-415740-tty-based-group-scheduling.md
- _posts/2019-09-19-14-20-55-rtlinux-latency-tracing.md
> post: publish rtlinux-latency-tracing

- _posts/2019-09-20-11-10-59-tinylab-weekly-09-3rd-2019.md
- _posts/2019-09-23-16-04-33-characters-match-in-shell.md
> post: publish characters-match-in-shell

- _posts/2019-09-24-10-37-57-lwn-418884-group-scheduling-and-alternatives.md
> post: publish lwn-418884-group-scheduling-and-alternatives

- _posts/2019-09-27-09-43-10-tinylab-weekly-09-4th-2019.md
- _posts/2019-09-30-08-19-08-android-signature.md
> post: publish android-signature

- _posts/2019-10-08-10-52-57-lwn-433904-a-group-scheduling-demo.md
> post: publish lwn-433904-a-group-scheduling-demo

- _posts/2019-10-14-08-57-57-guide-to-novnc.md
> post: publish guide-to-novnc

- _posts/2019-10-15-09-51-39-lwn-106010-approaches-to-rt-linux.md
> post: publish lwn-106010-approaches-to-rt-linux

- _posts/2019-10-17-09-52-28-lwn-two-years-anniversary.md
> post: publish lwn-two-years-anniversary

- _posts/2019-11-26-08-58-17-lxr-services-and-tools.md
> post: publish lxr-services-and-tools

- _posts/2019-11-23-17-15-07-lwn-302043-moving-int-to-threads.md
- _posts/2019-11-26-10-21-15-lwn-452884-per-cpu-var-and-rt-tree.md
> post: publish lwn-452884-per-cpu-var-and-rt-tree

- _posts/2019-11-28-13-29-47-linux-multi-screens-usage.md
> post: publish linux-multi-screens-usage

- _posts/2019-11-29-09-26-40-tinylab-weekly-11-4th-2019.md
- _posts/2019-12-02-09-18-48-git-speedup.md
> post: publish git-speedup

- _posts/2019-12-04-09-07-07-liteos-env-setup.md
> post: publish liteos-env-setup

- _posts/2019-12-04-09-11-30-lwn-520076-softirq-realtime.md
> post: publish lwn-520076-softirq-realtime

- _posts/2019-12-05-08-42-57-360-elf-lab.md
- _posts/2019-12-05-11-45-02-liteos-kernel-tasks.md
> post: publish 360-elf-lab & liteos-kernel-tasks

- _posts/2019-12-06-20-47-31-tinylab-weekly-12-1st-2019.md
- _posts/2019-12-11-11-17-48-main-return.md
> post: publish main-return

- _posts/2019-12-26-10-42-15-tinylab-weekly-12-4th-2019.md
- _posts/2019-12-30-09-37-04-latest-linux-code.md
> post: publish latest-linux-code

- _posts/2020-01-03-14-33-35-tinylab-weekly-01-1st-2020.md
- _posts/2020-01-07-08-59-26-d-state-processes-stuck-in-shrink_inactive_list.md
> post: publish d-state-processes-stuck-in-shrink_inactive_list

- _posts/2020-01-07-08-59-26-d-state-processes-stuck-in-shrink_inactive_list.md
- _posts/2020-01-09-08-41-52-pwntools-intro.md
> post: publish pwntools-intro

- _posts/2020-01-10-09-43-24-tinylab-weekly-01-2nd-2020.md
- _posts/2020-01-13-08-57-18-kernel-script-config.md
> post: publish kernel-script-config

- _data/people.yml
Signed-off-by: Murongfeng2018 <hkli2013@126.com>
> Modify the info of Feng Li

- _posts/2020-01-13-08-57-18-kernel-script-config.md
- _posts/2020-01-14-08-48-58-lwn-646950-reinventing-the-timer-wheel.md
> post: publish lwn-646950-reinventing-the-timer-wheel

- _posts/2020-01-14-08-48-58-lwn-646950-reinventing-the-timer-wheel.md
- _posts/2020-01-15-08-41-42-linux-product-evaluate-size-and-boot.md
> post: publish linux-product-evaluate-size-and-boot

- _posts/2020-02-05-19-57-51-lwn-808048-KRSI-the-other-BPF-security-module.md
Signed-off-by: Murongfeng2018 <hkli2013@126.com>
> lwn 808048: KRSI — the other BPF security module
